version: '2'
services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/soccerleague
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_NAME: soccerleague
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: estagiario
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
